---

- name: Install Apache2
  package:
    name: apache2
    state: latest

- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: Configure Apache2
  template:
    src: vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.key }}.conf"
  with_dict: "{{ apache_vhosts }}"
  notify:
    - restart apache

- include_tasks: disable_default.yml

- name: Enable vhosts
  file:
    src: "/etc/apache2/sites-available/{{ item.key }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.key }}.conf"
    owner: root
    group: root
    state: link
  with_dict: "{{ apache_vhosts }}"
  notify:
    - restart apache

- name: Enable/start Apache service
  systemd:
    name: apache2
