---

- name: Pull NodeBB repo
  git:
    repo: https://github.com/NodeBB/NodeBB.git
    dest: /var/www/forum.example.com
    version: "{{ nodebb.version }}"

- name: Configure NodeBB
  template:
    src: config.json.j2
    dest: /var/www/forum.example.com/config.json

- name: Install NodeBB
  npm:
    path: /var/www/forum.example.com/
    production: yes
