---

- name: Ensure Magento directory structure
  file:
    path: /var/www/shop.example.com/magento/
    owner: www-data
    group: www-data
    state: directory

- name: Fetch Magento 2 archive
  get_url:
    url: "https://github.com/magento-2/magento-2-community-sample-data/archive/master.tar.gz"
    dest: /var/www/shop.example.com/magento.tar.gz
    owner: www-data
    group: www-data

- name: Check for Magento index.php
  stat:
    path: /var/www/shop.example.com/magento/index.php
  register: magento_index

- name: Extract Magento archive
  unarchive:
    remote_src: true
    src: /var/www/shop.example.com/magento.tar.gz
    dest: /var/www/shop.example.com/magento/
    owner: www-data
    group: www-data
    extra_opts: ["--strip-components=1"]
  when: not magento_index.stat.exists # Hack to save time by skipping large archive search
