---

- name: Add Bedrock apt key
  apt_key:
    url: https://apt.bedrockdb.com/bedrock.gpg
    state: present

- name: Add Bedrock apt source
  apt_repository:
    repo: deb https://apt.bedrockdb.com/ubuntu/ xenial main
    state: present
    filename: 'bedrockdb'

- name: Configure Bedrock
  template:
    src: bedrock.init.j2
    dest: /etc/init.d/bedrock
    owner: root
    group: root
    mode: 0755
  notify:
    - reload systemd
    - restart bedrock

- name: Install Bedrock
  package:
    name: bedrock
    state: latest
