---

- name: remove lock
  file:
    path: /tmp/deploy.lock
    state: absent

- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted

- name: log build
  lineinfile:
    path: '/var/www/{{ domain }}/deployed_builds'
    line: '{{ build_number }}'
