---

- name: Check that project directory exists
  file:
    path: "{{ project_path }}"
    state: directory

- name: Download {{ project_name }} archive
  get_url:
    url: "{{ project_download }}"
    dest: "{{ project_web_root }}/{{ project_name }}.tar.gz"
    mode: 0755

- name: Extract archive
  unarchive:
    src: "{{ project_web_root }}/{{ project_name }}.tar.gz"
    dest: "{{ project_path }}"
    copy: no
