---

- name: Install web packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items: "{{ web_packages }}"

- include: nginx.yml
- include: joomla.yml
- include: php.yml
