---

- name: Ensure NGINX is started
  service:
    name: nginx
    state: started

- name: Remove default server block
  file:
    path: /etc/nginx/sites-enabled/default.conf
    state: absent

- name: Create {{ project_name }} server block
  template:
    src: joomla.serverblock.j2
    dest: /etc/nginx/sites-available/joomla.conf

- name: Enable {{ project_name }} server block
  file:
    src: /etc/nginx/sites-available/joomla.conf
    dest: /etc/nginx/sites-enabled/joomla.conf
    state: link
