---

- name: Enable PATH_INFO support
  lineinfile:
    dest: /etc/php5/fpm/php.ini
    regexp: "^cgi.fix_pathinfo="
    line: "cgi.fix_pathinfo=0"
    state: present
  notify:
    - restart php
    - restart nginx
