---

# - name: Pull build {{ build_number }} artifacts

# - name: Validate artifact

- name: Create release directory
  file:
    path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
    state: directory
    with_items:
      - 'app/etc/'
      - 'pub'

- name: Symlink shared assets
  file:
    src: '/var/www/{{ domain }}/shared/{{ item }}'
    dest: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
    state: link
    with_items:
      - 'app/etc/env.php'
      - 'pub/media'
      - 'var'

- name: Clean shared caches
  file:
    path: '/var/www/{{ domain }}/shared/var/{{ item }}'
    state: absent
    recurse: yes
    with_items:
      - 'cache'
      - 'di'
      - 'generation'
      - 'page_cache'
      - 'view_preprocessed'

- name: Extract archive
  unarchive:
    remote_src: true
    src: '/tmp/magento.tar.gz'
    dest: '/var/www/{{ domain }}/releases/{{ build_number }}/'

- name: Set file permissions
  file:
    path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
    state: file
    mode: 'g+w'
    with_items:
      - 'var'
      - 'vendor'
      - 'pub/static'
      - 'pub/media'
      - 'app/etc'

- name: Set directory permissions
  file:
    path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
    state: directory
    mode: 'g+ws'
    with_items:
      - 'var'
      - 'vendor'
      - 'pub/static'
      - 'pub/media'
      - 'app/etc'

- name: Set ownership
  file:
    path: '/var/www/{{ domain }}/releases/{{ build_number }}/'
    owner: '{{ user }}'
    group: '{{ web_server_group }}'
    recurse: yes
