---

- name: Magento setup:upgrade
  command: bin/magento setup:upgrade --keep-generated
  args:
    chdir: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/'

- name: Magento deploy:mode:set
  command: bin/magento deploy:mode:set production --skip-compilation
  args:
    chdir: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/'

- name: Magento cache:flush
  command: bin/magento cache:flush
  args:
    chdir: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/'
