---

- block:
  - name: Get name of project user
    local_action: command whoami
    become: false
    register: project_user
    changed_when: false

  - include: retrieve_archive.yml
  - include: prepare_filesystem.yml
  - include: symlnk_release.yml
  - include: magento.yml

  rescue:
    - set_fact:
        deploy_failure: "FAILED!"

  always:
    - include: notify_slack.yml
    - notify: remove lock
