---

# - name: Pull build {{ build_number }} artifacts

# - name: Validate artifact

- name: Create release directory
  file:
    path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
    state: directory
    with_items:
      - 'app/etc/'
      - 'pub'

- name: Symlink shared assets
  file:
    src: '/var/www/{{ domain }}/shared/{{ item.src }}'
    dest: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item.dest }}'
    state: link
    with_items:
      - 'app/etc/env.php'
      - 'pub/media'
      - 'var'

- name: Clean shared caches
  file:
    path: '/var/www/{{ domain }}/shared/var/{{ item }}'
    state: absent
    recurse: yes
    with_items:
      - 'cache'
      - 'di'
      - 'generation'
      - 'page_cache'
      - 'view_preprocessed'
