---

- name: Get MD5 checksum
  set_fact:
    md5_checksum: "{{ item }}"
  with_url: 'https://{{ build_number }}-{{ project_number }}-gh.circle-artifacts.com/0/tmp/checksum.md5?circle-token={{ circle_token }}'

- name: Pull archive if necessary
  get_url:
    url: 'https://{{ build_number }}-{{ project_number }}-gh.circle-artifacts.com/0/tmp/{{ item }}?circle-token={{ circle_token }}'
    dest: '/tmp/artifacts/magento.tar.gz'
    checksum: "md5:{{ md5_checksum }}"
