---

- hosts: all
  tasks:
    - name: Install WireGuard
      block:
        - name: Add WireGuard PPA
          apt_repository:
            repo: 'ppa:wireguard/wireguard'

        - name: Install WireGuard and dependencies
          package:
            name: "{{ item }}"
            state: present
          with_items:
            - wireguard-dkms
            - wireguard-tools
