---

- hosts: web
  tasks:
    - name: Fetch MD5 artifact
      set_fact:
        md5_checksum: "{{ item }}"
      with_url: 'https://{{ build_number }}-{{ project_number }}-gh.circle-artifacts.com/0/tmp/checksum.md5?circle-token={{ circle_token }}'

    - name: Pull Magento artifact # Only pulls if 'dest' doest not exists or if 'dest' fails MD5 check
      get_url:
        url: 'https://{{ build_number }}-{{ project_number }}-gh.circle-artifacts.com/0/tmp/magento.tar.gz?circle-token={{ circle_token }}'
        dest: '/tmp/arifacts/magento.tar.gz'
        checksum: "md5:{{ md5_checksum }}"

    - name: Create release directory structure
      file:
        path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
        state: directory
        with_items:
          - 'app/etc/'
          - 'pub'
            
    - name: Symlink shared assets
      file:
        src: '/var/www/{{ domain }}/shared/{{ item }}'
        dest: '/var/wwww/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
        state: link
        with_items:
          - 'app/etc/env.php'
          - 'pub/media'
          - 'pub/static'
          - 'var'

    - name: Clean shared caches
      file:
        path: '/var/www/{{ domain }}/shared/var/{{ item }}'
        state: absent
        recurse: yes
        with_items:
          - 'cache'
          - 'di'
          - 'generation'
          - 'page_cache'
          - 'view_preprocessed'

    - name: Extract archive
      unarchive:
        remote_src: true
        src: '/tmp/magento.tar.gz'
        dest: '/var/www/{{ domain }}/releases/{{ build_number }}/'

    - name: Set file permissions
      file:
        path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
        state: file
        mode: 'g+w'
        with_items:
          - 'var'
          - 'vendor'
          - 'pub/static'
          - 'pub/media'
          - 'app/etc'

    - name: Set directory permissions
      file:
        path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
        state: directory
        mode: 'g+ws'
        with_items:
          - 'var'
          - 'vendor'
          - 'pub/static'
          - 'pub/media'
          - 'app/etc'

    - name: Set ownership
      file:
        path: '/var/www/{{ domain }}/releases/{{ build_number }}/'
        owner: '{{ user }}'
        group: '{{ web_server_group }}'
        recurse: yes
    
    - name: Execute Magento setup:upgrade
      command: bin/magento setup:upgrade --keep-generated
      args:
        chdir: '/var/www/{{ domain }}/releases/{{ build_numer }}/magento/'

    - name: Symlink deployed release
      file:
        src: '/var/www/{{ domain }}/release/{{ build_number }}/'
        dest: '/var/www/{{ domain }}/current'
        state: link
      notify:
        - restart php-fpm

    - name: Execute Magento cache:flush
      command: bin/magento cache:flush
      args:
        chdir: '/var/www/{{ domain }}/releases/{{ build_numer }}/magento/'

  handlers:
    - name: restart php-fpm
      service:
        name: php-fpm
        state: restarted
