---

- hosts: web
  tasks:
    - name: Fetch MD5 artifact
      set_fact:
        md5_checksum: "{{ item }}"
      with_url: 'https://{{ build_number }}-{{ project_number }}-gh.circle-artifacts.com/0/tmp/checksum.md5?circle-token={{ circle_token }}'

    - name: Pull Magento artifact if necessary
      get_url:
        url: 'https://{{ build_number }}-{{ project_number }}-gh.circle-artifacts.com/0/tmp/magento.tar.gz?circle-token={{ circle_token }}'
        dest: '/tmp/arifacts/magento.tar.gz'
        checksum: "md5:{{ md5_checksum }}"

    - name: Create release directory
      file:
        path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
        state: directory
        with_items:
          - 'app/etc/'
          - 'pub'
            
    - name: Symlink shared assets
      file:
        src: '/var/www/{{ domain }}/shared/{{ item }}'
        dest: '/var/wwww/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
        state: link
        with_items:
          - 'app/etc/env.php'
          - 'pub/media'
          - 'pub/static'
          - 'var'

    - name: Clean shared caches
      file:
        path: '/var/www/{{ domain }}/shared/var/{{ item }}'
        state: absent
        recurse: yes
        with_items:
          - 'cache'
          - 'di'
          - 'generation'
          - 'page_cache'
          - 'view_preprocessed'

    - name: Extract archive
      unarchive:
        remote_src: true
        src: '/tmp/magento.tar.gz'
        dest: '/var/www/{{ domain }}/releases/{{ build_number }}/'

    - name: Set file permissions
      file:
        path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
        state: file
        mode: 'g+w'
        with_items:
          - 'var'
          - 'vendor'
          - 'pub/static'
          - 'pub/media'
          - 'app/etc'

    - name: Set directory permissions
      file:
        path: '/var/www/{{ domain }}/releases/{{ build_number }}/magento/{{ item }}'
        state: directory
        mode: 'g+ws'
        with_items:
          - 'var'
          - 'vendor'
          - 'pub/static'
          - 'pub/media'
          - 'app/etc'
