---

- hosts: tag_group_production
  tasks:
    - name: Update RDS endpoint
      replace:
        dest: /var/www/wordpress/wp-config.php
        regexp: "RDS_ENDPOINT"
        replace: "{{ rds_endpoint }}" # Defined on command line
