---

- name: Install Pound
  package:
    name: pound
    state: latest

- name: Enable Pound service
  lineinfile:
    path: /etc/default/pound
    regexp: '^startup'
    line: 'startup=1'

- name: Configure Pound
  template:
    src: pound.cfg.j2
    dest: /etc/pound/pound.cfg
    owner: root
    group: root
    mode: 0644
  notify:
    - restart pound
