---

- name: Install Elasticsearch
  package:
    name: elasticsearch
    state: latest

- name: Configure Elasticsearch
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "network.host: localhost"
    state: present

- name: Enable/start Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
