---

- name: Install Kibana
  package:
    name: kibana
    state: latest

- name: Configure Kibana
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: "server.host: 0.0.0.0"
    state: present

- name: Enable/start Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: started
