---

- name: Disable NGINX default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - restart nginx

- name: Remove default site files
  file:
    path: /usr/share/nginx/html/
    state: absent
