---

- name: Pull data from LastPass
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Register Magento public and private keys
      block:
        - name: Magento public key
          command: lpass show "{{ lastpass.magento.project }}/Magento Keys" --field=public_key
          register: magento_public_key
          changed_when: false
        - name: Magento private key
          command: lpass show "{{ lastpass.magento.project }}/Magento Keys" --field=private_key
          register: magento_private_key
          changed_when: false
      rescue:
        - debug: 
            msg: "Accessing LastPass failed, are you logged in?"
      become: false
