---

- name: Import Treasure Data GPG Key 
  rpm_key:
    state: present
    key: https://packages.treasuredata.com/GPG-KEY-td-agent


- name: Install Treasure Data repo
  yum_repository:
    name: treasuredata
    description: Treasure Data - Fluentd
    baseurl: http://packages.treasuredata.com/2/redhat/$releasever/$basearch
    gpgcheck: yes
    gpgkey: https://packages.treasuredata.com/GPG-KEY-td-agent
    enabled: yes

- name: Install fluentd via td-agent
  package:
    name: td-agent
    state: latest
