---

- name: Install common packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items: "{{ common_packages }}"

- name: Update hosts file
  lineinfile:
    dest: "/etc/hosts"
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups['all'] }}"
