---

- name: Fetch Magento 2 archive
  get_url:
    url: "https://github.com/magento-2/magento-2-community-sample-data/archive/master.tar.gz"
    dest: /var/www/{{ apache_vhosts.shop.domain }}/magento.tar.gz
    owner: www-data
    group: www-data

- name: Extract Magento archive
  unarchive:
    remote_src: true
    src: /var/www/{{ apache_vhosts.shop.domain }}/magento.tar.gz
    dest: /var/www/{{ apache_vhosts.shop.domain }}/magento/
    owner: www-data
    group: www-data
    extra_opts: ["--strip-components=1"]
    creates: /var/www/{{ apache_vhosts.shop.domain }}/magento/index.php
