---

- name: Ensure Magento directory structure
  file:
    path: /var/www/{{ apache_vhosts.shop.domain }}/magento/
    owner: www-data
    group: www-data
    mode: 0775
    state: directory

- include_tasks: composer_install.yml
- include_tasks: install_magento.yml
